### ISSUE TITLE
Country field populated with County

### ISSUE THREAD

**Issue by OkomelaIT** [ActiveIS/ActiveIS.UmbracoForms.Loqate#2]
Hello Aaron,

Thanks for all the work you have done on this.

I have come across the following error. 

The country field is being populated with the **County** information.
I notice the following code in FieldType.Loqate.cshtml - line 279

```
                        @if (!string.IsNullOrEmpty(countryAlias))
                        {
                            <text>$('.@countryAlias').val(res.AdminAreaName);</text>
                        }  
```      
I had a look at the response options and there wasn't one for **Country**. 
Is there a quick work around for this or should I try implementing the newer API?

Thanks   

Clinton

**Comment by OkomelaIT** [comment]
Hiya Aaron,

I have sorted this one.

Updated the code to:

```
 @if (!string.IsNullOrEmpty(countryAlias))
                        {
                            <text>$('.@countryAlias').val(res.CountryName);</text>
                        }
```

Thanks

**Comment by AaronSadlerUK** [comment]
Ah I will fix this for the next version, thanks!

I have updated the dev branch to use ID's if you wanted to have a look.
https://github.com/ActiveIS/ActiveIS.UmbracoForms.Loqate/tree/develop
